### ISSUE TITLE
更正

### ISSUE THREAD

**Issue by huanggengzhong** [zwxs/frontInterview#1]
function A(a,b=1){
    console.log(a+b);
}

A(2,3);  //这里你写错了,你写成了2+3

**Comment by huanggengzhong** [comment]
#### 11题
Array.form()方法写错了.正确的是Array.from().这个错误很容易犯的,我个人的记忆是除了form表单外,其它一般都是from

**Comment by zwxs** [comment]
对对是from可能单词打错了现在是from了from 是开始 来源的意思 form是表单

**Comment by zwxs** [comment]
是的A(2,3) 也是可能当时写错了谢谢更正
